FORMAT: 1A
HOST: http://localhost:8080

# Google News Template API (v1.0.0)

Google News Template API is an API which allows consumers to interact with sample news content.

# Root [/]

## Status Check [GET]

This action allows consumers to verify the status of the server. A response status code `204` indicates that the server is healthy.

+ Response 204 (application/json)

## Categories [/api/v1/categories]

Resources related to news categories.

### Get Categories [GET]

This action allows you to query all available news categories.

+ Response 200 (application/json)
    + Attributes (object)
        + categories (required, array[Category]) - The list of available news categories.

    + Body
        
            {
                "categories": [
                    "technology",
                    "sports",
                    "top"
                ]                
            }

## Feed [/api/v1/feed{?category,limit,offset}]

Resources related to the news feed.

+ Parameters
    + category (optional, Category) - The headline category.
        + Default: general
        + Members            
            + business
            + entertainment
            + general
            + health
            + science
            + sports
            + technology
    + limit (optional, number) - The number of results to return.
        + Default: 20
    + offset (optional, number) - The (zero-based) offset of the first item in the collection to return.
        + Default: 0

### Get Feed [GET]

This action allows you to query feeds.

+ Response 200 (application/json)
    + Attributes (object)
        + feed (required, array[Block]) - The list of blocks that composes the feed.
        + total_count (optional, number) - The total number of available blocks.

    + Body
        
            {
                "feed": [
                    {
                        "title": "Breaking News",
                        "type": "__section_header__"
                    },
                    {
                        "type": "__divider_horizontal__"
                    },
                    {
                        "type": "__spacer__",
                        "spacing": "medium"
                    }
                ],
                "total_count": 100,
            }

# Data Structures

## Block (object)

+ type (required, BlockType) - the block type.

## BlockType (enum)

+ "__section_header__" - a section header block
+ "__divider_horizontal__" - a divider horizontal block
+ "__spacer__" - a spacer block
+ "__unknown__" - an unrecognized block

## Category (enum)

+ business - news relating to business
+ entertainment - news relating to entertainment
+ top - breaking news 
+ health - news relating to health
+ science - news relating to science
+ sports - news relating to sports
+ technology - news relating to technology