part of 'widgets/terms_of_service_body.dart';

const String termsOfServiceMockText =
    'Curabitur vel volutpat eros, in interdum eros.Pellentesque lorem magna, '
    'facilisis vel diam nec, sagittis fermentum purus. '
    'Maecenas placerat urna ullamcorper ultrices elementum. '
    'Quisque maximus lectus ac posuere posuere. Fusce eu molestie libero. '
    'Nulla fringilla enim et elit facilisis blandit. '
    '\n\nEtiam tincidunt porta vulputate. '
    'Maecenas congue convallis odio sit amet pharetra. '
    '\nPhasellus sagittis dapibus erat non sagittis. '
    'Praesent imperdiet lectus urna, a sagittis sapien pulvinar vel. '
    'Orci varius natoque penatibus et magnis dis parturient montes, '
    'nascetur ridiculus mus. Proin eget neque turpis. '
    'Quisque a lectus feugiat, sollicitudin massa ac, ultricies tellus. '
    'Proin rutrum neque nec vehicula ultrices. Suspendisse venenatis odio mi. '
    'Sed dictum congue nisi id finibus. '
    '\n\nMorbi malesuada lorem est '
    'Phasellus eget mi risus. Nulla facilisi . '
    'Aliquam fermentum malesuada metus, nec pretium odio efficitur in. '
    'In condimentum semper ipsum quis cursus. '
    'Aenean in ex at leo porta ultrices. '
    'Curabitur vel volutpat eros, in interdum eros. '
    '\n\nPellentesque lorem magna, facilisis vel diam nec, '
    'sagittis fermentum purus. '
    'Maecenas placerat urna ullamcorper ultrices elementum. '
    'Quisque maximus lectus ac posuere posuere. '
    'Fusce eu molestie libero. Nulla fringilla enim et elit facilisis blandit. '
    'Etiam tincidunt porta vulputate. '
    'Maecenas congue convallis odio sit amet pharetra. '
    'Phasellus sagittis dapibus erat non sagittis. '
    'Praesent imperdiet lectus urna, a sagittis sapien pulvinar vel. '
    'Orci varius natoque penatibus et magnis dis parturient montes, '
    'nascetur ridiculus mus. Proin eget neque turpis. '
    'Quisque a lectus feugiat, sollicitudin massa ac, ultricies tellus. '
    'Proin rutrum neque nec vehicula ultrices. '
    'Suspendisse venenatis odio mi. Sed dictum congue nisi id finibus. '
    'Morbi malesuada lorem est, id efficitur mauris ultrices sit amet. '
    'Phasellus eget mi risus. Nulla facilisi. '
    'Aliquam fermentum malesuada metus, nec pretium odio efficitur in. '
    'In condimentum semper ipsum quis cursus. '
    'Aenean in ex at leo porta ultrices. ';
